[build]
  functions = "functions"
  publish = "/"

[dev]
  functions = "functions"
  publish = "src"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.groq.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://images.unsplash.com; script-src 'self' https://cdn.jsdelivr.net https://www.google.com https://www.gstatic.com; frame-src 'self' https://www.google.com https://www.gstatic.com; object-src 'none'; base-uri 'self'"

# Rate limiting using Netlify Edge Functions
[[edge_functions]]
  path = "/.netlify/functions/chat"
  function = "rate-limit"
  
[[redirects]]
  from = "/.netlify/functions/chat"
  to = "/.netlify/functions/chat"
  status = 200
  edge_function = "rate-limit"