[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.groq.com;"

# Rate limiting using Netlify Edge Functions
[[edge_functions]]
  function = "rate-limit"
  path = "/api/*"